### ISSUE TITLE
Could you run the LTSD ?

### ISSUE THREAD

**Issue by ucasiggcas** [emilmelnikov/speaker-identification#1]
Dear,

when I use the LTSD with vad.py
it tells me,
`if not x[i]:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`
So 
could I use `if not np.any(x[i]):` ?
Thx

**Comment by ucasiggcas** [comment]
I have try `np.any(x[i])` and `np.all(x[i]),but` the results are the same,

I find when noise last long, the results are not good,
you can see the pic down
![image](https://user-images.githubusercontent.com/35590066/59193609-d547b300-8bb8-11e9-8cc6-17b07b61b675.png)
and the wav file is here,you can have a try
[1.zip](https://github.com/emilmelnikov/speaker-identification/files/3271928/1.zip)

and the second is not very good ,either
![image](https://user-images.githubusercontent.com/35590066/59193808-7898c800-8bb9-11e9-8e6a-2d3f8286137d.png)
[g19.zip](https://github.com/emilmelnikov/speaker-identification/files/3271936/g19.zip)

**Comment by ucasiggcas** [comment]
who can try the wav file  Use the code?
Thx

**Comment by emilmelnikov** [comment]
@ucasiggcas Hi, sorry for the late 2-year response, I didn't intend this repo to be used by someone else, and haven't seen this issue for some reason.

I've re-skimmed the paper, and, apparently, I had a typo: the paper says that you should update the noise spectrum if speech pause is detected, so instead of `if not x[i]:` one should use `if mask[i]:`.

Regarding the applicability to your dataset: I'd suggest to play with the algorithm's hyperparameters: thresholds, energy levels, or number of hangover frames.

I will commit the change, but, to be honest, I wouldn't recommend using this code. There are probably much more robust VAD methods and their implementations out there.
